PREBUILT_PATH := $(call my-dir)
LOCAL_PATH         := $(PREBUILT_PATH)
include $(CLEAR_VARS)
LOCAL_MODULE :=	SWE_AndroidBrowser111.apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)